In [1]:
import tensorflow as tf
tf.__version__

'2.8.2'

In [2]:
mnist = tf.keras.datasets.mnist
(x_train , y_train) , (x_test , y_test) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [3]:
x_train , x_test = x_train/255.0 , x_test /255.0 

In [5]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)),
    tf.keras.layers.Dense(128 , activation= 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [7]:
prediction = model(x_train[:1]).numpy()
prediction

array([[ 0.17244452,  0.737285  ,  0.03561604,  0.44634402,  0.3408723 ,
         0.36192334,  0.18332417, -0.46351266,  0.12986074,  0.05007416]],
      dtype=float32)

In [8]:
tf.nn.softmax(prediction).numpy()

array([[0.09326679, 0.16407187, 0.08133981, 0.12265354, 0.1103759 ,
        0.11272406, 0.09428704, 0.04937809, 0.08937851, 0.08252438]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True)

In [10]:
loss_fn(y_train[:1] , prediction).numpy()

2.1828122

In [12]:
model.compile(optimizer = 'adam' , loss= loss_fn , metrics = ['accuracy'])

In [13]:
model.fit(x_train , y_train , epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2932 - accuracy: 0.9153
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1440 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1072 - accuracy: 0.9668
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0885 - accuracy: 0.9724
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0758 - accuracy: 0.9769


In [15]:
model.evaluate(x_test , y_test , verbose = 2)

313/313 - 1s - loss: 0.0736 - accuracy: 0.9793 - 899ms/epoch - 3ms/step


[0.07355741411447525, 0.9793000221252441]

In [16]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])

In [17]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.77921016e-08, 1.20216356e-07, 1.75217360e-06, 2.33360974e-04,
        3.04126273e-11, 8.31819125e-06, 3.33885593e-11, 9.99754488e-01,
        1.26673524e-06, 6.03181775e-07],
       [4.35923333e-08, 6.28403868e-05, 9.99933958e-01, 2.78746006e-06,
        1.32654804e-15, 1.21700864e-07, 1.23044813e-07, 1.06259207e-12,
        1.04536475e-07, 1.36691073e-13],
       [4.60230680e-08, 9.98903871e-01, 4.35573384e-05, 6.06303593e-06,
        9.11332972e-05, 5.55541965e-06, 2.18849982e-06, 9.01969324e-04,
        4.15932336e-05, 3.99385863e-06],
       [9.99662042e-01, 8.45783390e-08, 1.32546658e-04, 5.34164258e-07,
        1.16842882e-08, 5.41666195e-05, 1.62502183e-05, 1.30940112e-04,
        3.15470206e-09, 3.35900108e-06],
       [3.73236726e-05, 6.56302612e-09, 1.62978962e-04, 4.16220416e-07,
        9.72221613e-01, 3.51548260e-05, 1.29630398e-05, 7.03088474e-04,
        2.97568295e-05, 2.67968159e-02]], dtype=float32)>